# Generated by Django 2.2.1 on 2019-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Quiz title', max_length=100)),
                ('description', models.TextField(help_text='Quiz description')),
                ('pubdate', models.DateTimeField(help_text='When should the quiz be published?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='Optional date the task is due to', null=True)),
            ],
            options={
                'ordering': ['deadline', 'pubdate', 'title'],
            },
        ),
    ]
