# Generated by Django 2.2.1 on 2019-05-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0001_initial'),
        ('quizzes', '0003_hashtag_quizhashtagrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='compilation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compilations.Compilation'),
        ),
    ]
