import re

from django.db import models
from django.db.transaction import atomic

from fragenkatalog.quizzes.models import Quiz


class Question(models.Model):
    # mandatory fields
    description = models.CharField(max_length=10000, default="")
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    # autogenerated fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # optional fields
    description_image = models.ImageField(upload_to="images", null=True, blank=True)
    solution_image = models.ImageField(upload_to="images", null=True, blank=True)

    def __str__(self):
        return "({}) {}".format(self.quiz, self.description)

class TextualQuestion(Question):
    # mandatory fields
    solution = models.CharField(max_length=10000, default="")
