from django.db import models

from fragenkatalog.quizzes.models import Quiz


class TextualQuestion(models.Model):
    # mandatory fields
    description = models.CharField(max_length=1000)
    solution = models.CharField(max_length=1000)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    # autogenerated fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # optional fields
    image = models.ImageField(upload_to="images", null=True, blank=True)
