# Generated by Django 2.2.1 on 2019-05-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190522_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textualquestion',
            name='position',
        ),
    ]
