# Generated by Django 2.2 on 2019-07-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190709_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='description_image',
        ),
        migrations.AddField(
            model_name='question',
            name='solution_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
