# Generated by Django 2.2.1 on 2019-05-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_compilation'),
        ('questions', '0003_remove_textualquestion_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz')),
            ],
        ),
        migrations.RemoveField(
            model_name='textualquestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='textualquestion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='textualquestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='textualquestion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='textualquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='textualquestion',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question')),
            ],
            bases=('questions.question',),
        ),
        migrations.AddField(
            model_name='textualquestion',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solution', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.MultipleChoiceQuestion')),
            ],
        ),
    ]
