# Generated by Django 2.2.1 on 2019-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190528_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoiceoption',
            name='description',
            field=models.CharField(default='Hallo', max_length=1000),
            preserve_default=False,
        ),
    ]
