# Generated by Django 2.2.1 on 2019-05-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_multiplechoiceoption_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoiceoption',
            old_name='description',
            new_name='option_description',
        ),
    ]
