from django.db import models

# Create your models here.
import re

from django.db import models
from django.utils import timezone
from django.utils.text import slugify


class Quiz(models.Model):
    """Represents the quizzes that are presented to the user to solve."""

    class Meta:
        ordering = ["deadline", "pubdate", "title"]

    # mandatory fields
    title = models.CharField(max_length=100, help_text="Quiz title")
    description = models.TextField(help_text="Quiz description")
    pubdate = models.DateTimeField(help_text="When should the quiz be published?")

    # autogenerated fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # optional fields
    deadline = models.DateTimeField(help_text="Optional date the task is due to", null=True, blank=True)
    image = models.ImageField(upload_to="images", null=True, blank=True)

    @property
    def is_published(self):
        """Return True if the task is already visible to the users."""
        return timezone.now() > self.pubdate

    @property
    def is_expired(self):
        """Return True if the task has passed its optional deadline."""
        return self.deadline and timezone.now() > self.deadline

    @property
    def sluggable_title(self):
        """Return the title with anything between parentheses removed."""
        return re.sub(r'\(.*?\)', '', self.title)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.sluggable_title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

"""
quiz1 = Quiz.objects.create(
    title="Microbiology Quiz",
    description="Interactive Microbiology Quiz",
    pubdate=timezone.now()
)
quiz2 = Quiz.objects.create(
    title="Gene Technology Quiz",
    description="Interactive Gene Technology Quiz",
    pubdate=timezone.now()
)
"""
