from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

from fragenkatalog.social.models import Like


class Compilation(models.Model):
    # mandatory fields
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)

    # autogenerated fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # optional fields
    image = models.ImageField(upload_to="images", null=True, blank=True)

    # generic relation fields
    likes = GenericRelation(Like)

    @property
    def likers(self):
        return set(like.created_by for like in self.likes.all())

    def liked_by(self, user):
        return self.likes.filter(created_by=user).exists()

    def __str__(self):
        return "<Compilation %s>" % self.title
