# Generated by Django 2.2.1 on 2019-05-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cookie',
        ),
        migrations.DeleteModel(
            name='Likeable',
        ),
    ]
